// Shared transport semantics; authority is checked by the executor dispatch.
export const readOnly = new Set(['services', 'requests', 'request.status', 'policies', 'enrollments', 'peers', 'providers', 'provider.check', 'accounts.search', 'browser.export', 'browser.observe', 'auth.status', 'auth.wait', 'takeover.observe', 'passkey.observe']);

// Finite operation catalogue for validating transport classifications at startup.
export const operations = new Set([
  'accounts.search',
  'accounts.select',
  'auth.cancel',
  'auth.request',
  'auth.status',
  'auth.wait',
  'browser.click',
  'browser.close',
  'browser.export',
  'browser.navigate',
  'browser.observe',
  'browser.open',
  'browser.type',
  'enrollment.put',
  'enrollments',
  'passkey.click',
  'passkey.key',
  'passkey.observe',
  'passkey.type',
  'peer.revoke',
  'peers',
  'policies',
  'policy.revoke',
  'provider.check',
  'provider.discovery',
  'provider.put',
  'provider.remove',
  'providers',
  'request.decide',
  'request.retry',
  'request.status',
  'requests',
  'services',
  'takeover.click',
  'takeover.finish',
  'takeover.key',
  'takeover.observe',
  'takeover.start',
  'takeover.type',
]);
